### ISSUE TITLE
Add Nolan's Clojure/nyc talk to Docs

### ISSUE THREAD

**Issue by ethland** [NuID/site#79]
[Link](https://www.youtube.com/watch?v=zdX-uUqPjqs)
Title: Macroservices - Datomic & the Web from the REPL with Nolan Smith
Publication: Clojure/nyc
Category: Educational
Date: 5/27/2020

**Comment by notalwaysgray** [comment]
https://github.com/NuID/site/commit/86ddea8df47b59e23343cd6247ad3f8d44861b1c
