### ISSUE TITLE
Correct typo on the explainer video in Docs

### ISSUE THREAD

**Issue by ethland** [NuID/site#92]
The explainer video on the [Docs page](https://nuid.io/#/docs) has the title "NuID: Trustless **Authentcation**" (typo bolded).

**Comment by notalwaysgray** [comment]
and we want **`Authention`**, no?

**Comment by ethland** [comment]
I thought we decided on **`Authentition`**?

**Comment by notalwaysgray** [comment]
https://github.com/NuID/site/commit/e7d2d2925169a2ce508a00d545e991bab67d518b
